version: '2'
services:
  ccriserver:
    container_name: ccriserver
    image: ${REGISTRY_PREFIX}ccri-fhirserver${IMAGE_TAG}
    depends_on:
      - ccrisql
    links:
      - ccrisql
    environment:
      - datasource.username=${MYSQL_DB_USER}
      - datasource.password=${MYSQL_DB_PASSWORD}
      - datasource.host=//ccrisql
      - datasource.driver=org.postgresql.Driver
      - datasource.path=5432/careconnect
      - datasource.vendor=postgresql
      - datasource.showSql=true
      - datasource.showDdl=true
      - datasource.cleardown.cron=0 19 21 * * *
      - datasource.dialect=org.hibernate.dialect.PostgreSQL9Dialect
      - datasource.ui.serverBase=${FHIR_SERVER_BASE_PROTOCOL}://${FHIR_SERVER_BASE_HOST}/ccri/fhir/STU3
      - datasource.serverBase=${FHIR_SERVER_BASE_PROTOCOL}://${FHIR_SERVER_BASE_HOST}/ccri/fhir/STU3
    extra_hosts:
      # Define an alias to loop back for REST Connections
      - "${FHIR_SERVER_BASE_HOST}:127.0.0.1"
    volumes:
      - tomcat-log-volume:/usr/local/tomcat/logs
    networks:
      ccri_net:
        ipv4_address: 172.168.240.10

  ccrisql:
    container_name: ccrisql
    image: ${REGISTRY_PREFIX}ccri-sql${IMAGE_TAG}
    environment:
      - POSTGRES_DB=careconnect
      - POSTGRES_USER=${MYSQL_DB_USER}
      - POSTGRES_PASSWORD=${MYSQL_DB_PASSWORD}
    networks:
      - ccri_net

  ccrifhir:
    container_name: ccrifhir
    image: ${REGISTRY_PREFIX}ccri-fhir${IMAGE_TAG}
    environment:
      - datasource.ui.serverBase=${FHIR_SERVER_BASE_PROTOCOL}://${FHIR_SERVER_BASE_HOST}/ccri-fhir/STU3
      - fhir.resource.serverBase=${FHIR_SERVER_BASE_PROTOCOL}://${FHIR_SERVER_BASE_HOST}/ccri-fhir/STU3
      - fhir.restserver.serverBase=http4://ccriserver:8080/careconnect-ri/STU3?throwExceptionOnFailure=false&bridgeEndpoint=true
      - fhir.restserver.edmsBase=http4://ccridocument:8181/STU3?throwExceptionOnFailure=false&bridgeEndpoint=true
      - fhir.restserver.tieBase=http4://ccritie:8182/STU3?throwExceptionOnFailure=false&bridgeEndpoint=true
    depends_on:
      - ccriserver
    ports:
      - 8105:80
    extra_hosts:
      - "${FHIR_SERVER_BASE_HOST}:172.168.240.10"
    volumes:
      - gateway-log-volume:/usr/local/tomcat/logs
    networks:
      ccri_net:
        ipv4_address: 172.168.240.14

  ccriui:
    container_name: ccriui
    image: ${REGISTRY_PREFIX}ccri-ui${IMAGE_TAG}
    environment:
      - datasource.ui.serverBase=http://${FHIR_SERVER_BASE_HOST}/ccri-fhir/STU3
      - fhir.resource.serverBase=${FHIR_SERVER_BASE_PROTOCOL}://${FHIR_SERVER_BASE_HOST}/ccri-fhir/STU3
      - fhir.restserver.serverBase=http4://${FHIR_SERVER_BASE_HOST}/careconnect-ri/STU3?throwExceptionOnFailure=false&bridgeEndpoint=true
      - fhir.restserver.edmsBase=http4://127.0.0.1:8184/STU3?throwExceptionOnFailure=false&bridgeEndpoint=true
    depends_on:
      - ccrifhir
    ports:
      - 8104:80
    extra_hosts:
      # Define an alias to the CCRI Container to ensure that the correct Server Base is displayed by HAPI
      - "${FHIR_SERVER_BASE_HOST}:172.168.240.14"
    networks:
      - ccri_net

  ccrimongo:
      container_name: ccrimongo
      image: mongo:3.6.3
      networks:
        - ccri_net

  ccridocument:
     container_name: ccridocument
     image: ${REGISTRY_PREFIX}ccri-document${IMAGE_TAG}
     depends_on:
       - ccrimongo
     links:
       - ccrimongo
     environment:
       - fhir.resource.serverBase=http://127.0.0.1:8080/careconnect-gateway/STU3
       - fhir.resource.serverName=Care Connect RI FHIR Server
       - fhir.resource.serverVersion=3.5.1-SNAPSHOT
       - spring.data.mongodb.uri=mongodb://ccrimongo:27017/careconnect-nosql
       - spring.data.mongodb.database=careconnect-nosql
     ports:
       - 8108:8181
     volumes:
       - mongo-log-volume:/usr/local/tomcat/logs
     networks:
       ccri_net:
         ipv4_address: 172.168.240.11

  oauthsql:
    container_name: oauthsql
    image: postgres:10.4
    environment:
    - POSTGRES_DB=oic
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=password
    networks:
    - oauth_net

  oauthserver:
    container_name: ccri_oauth_server
    image: ${REGISTRY_PREFIX}ccri-oauthserver
    environment:
    - oidc.issuer=v
    - ldap.url=ldap://oauthldap
    - ldap.server=ldap://oauthldap/dc=ccri,dc=com
    - oidc.datasource.mysql.schema=oic
    - oidc.datasource.mysql.url=jdbc:postgresql://oauthsql:5432/oic
    - JAVA_OPTIONS=-Dspring.profiles.active=local,users-keycloak,docker-purple
    - hspc.platform.accountLoginPage=https://${FHIR_SERVER_BASE_HOST}/document-viewer/
    - hspc.platform.accountLogoutPage=https://${FHIR_SERVER_BASE_HOST}/document-viewer/logout
    ports:
    - 8107:8080
    depends_on:
    - oauthsql
    networks:
    - oauth_net


networks:
  ccri_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.168.240.0/24
  oauth_net:
    driver: bridge
    ipam:
      driver: default

